### ISSUE TITLE
Question: Is it possible to limit the data port range?

### ISSUE THREAD

**Issue by saravananrbs** [mooware/mooftpserv#8]
Hi,

Is it possible to limit the data port range?

Example : 1024 - 2048

Thanks in advance!

**Comment by mooware** [comment]
Currently I'm letting the operating system choose the port, and it will most likely use the IANA range for dynamic ports at 49152–65535 (https://en.wikipedia.org/wiki/Ephemeral_port). It would be possible to implement it so that it assigns ports from your suggested range, but it's not advisable in general, since it might be a range where people will put their server ports.

If you want to modify the assigned ports, you can change it here: https://github.com/mooware/mooftpserv/blob/a1b5d3565f155964dee715ccebcaadb11e054cff/lib/Session.cs#L759
